# Generated by Django 5.0 on 2024-02-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_track'),
    ]

    operations = [
        migrations.DeleteModel(
            name='track',
        ),
    ]
