# Generated by Django 5.0 on 2024-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_delete_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('quantitys', models.CharField(max_length=100)),
                ('proteins', models.FloatField()),
                ('carb', models.FloatField()),
                ('fats', models.FloatField()),
                ('vitamin', models.CharField(max_length=100)),
                ('imgs', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
    ]
