# Generated by Django 5.0 on 2024-02-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='carb',
            new_name='ca',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='fats',
            new_name='fa',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='imgs',
            new_name='im',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='names',
            new_name='na',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='proteins',
            new_name='pr',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='quantitys',
            new_name='qu',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='vitamin',
            new_name='vi',
        ),
    ]
