# Generated by Django 5.0 on 2024-02-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_food_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
