# Generated by Django 5.0 on 2024-02-14 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_alter_food_quantity_alter_track_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='favourite',
        ),
        migrations.AddField(
            model_name='food',
            name='fav',
            field=models.ManyToManyField(blank=True, default=False, related_name='favs', to=settings.AUTH_USER_MODEL),
        ),
    ]
